<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Clock, Document, Download, RefreshRight, VideoPause } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import StatusPill from '@/components/StatusPill.vue'
import { getApiErrorMessage, isUnauthorizedError } from '@/api/client'
import { asyncTaskApi, courseApi, documentApi } from '@/api/services'
import { normalizeWeeklyReport, type BackendAsyncTask, type CourseListItem, type WeeklyReportRequest } from '@/types'

const route = useRoute(); const router = useRouter()
const activeStatuses = new Set(['queued', 'processing', 'cancelling'])
const labels: Record<string, string> = { document_parse: '文档解析', weekly_report: '学习周报', plan_generation: '学习计划生成' }
const steps: Record<string, string> = { queued: '等待处理', queued_for_retry: '等待重新入队', loading_learning_data: '读取学习数据', aggregating_tasks: '汇总学习任务', aggregating_mastery: '汇总掌握度', building_report: '生成周报', cancellation_requested: '正在取消', cancelled_before_start: '开始前已取消', cancelled_by_user: '已按用户请求取消', completed: '处理完成', dispatch_failed: '派发失败' }
const tasks = ref<BackendAsyncTask[]>([]); const total = ref(0); const selected = ref<BackendAsyncTask | null>(null)
const statusFilter = ref('all'); const typeFilter = ref('all'); const loading = ref(false); const loadError = ref(''); const actionLoading = ref(false); const selectionError = ref('')
const courses = ref<CourseListItem[]>([]); const courseLoading = ref(false); const showCreate = ref(false); const createLoading = ref(false); const createError = ref('')
const exportingReport = ref(false); const exportError = ref(''); let timer: number | undefined; let version = 0; let failures = 0
const today = new Date(); const end = today.toISOString().slice(0, 10); const startDate = new Date(today); startDate.setDate(today.getDate() - 6)
const reportForm = ref<WeeklyReportRequest>({ start_date: startDate.toISOString().slice(0, 10), end_date: end, course_id: null })
const report = computed(() => selected.value?.task_type === 'weekly_report' ? normalizeWeeklyReport(selected.value.result_data) : null)
const hasActive = computed(() => tasks.value.some(item => activeStatuses.has(item.status)))
const message = (error: unknown, fallback: string) => isUnauthorizedError(error) ? '登录状态已失效，请重新登录' : getApiErrorMessage(error, fallback)
const dateText = (value: string | null) => value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '暂无'
function stopPolling() { if (timer !== undefined) window.clearTimeout(timer); timer = undefined }
function schedulePolling() { stopPolling(); if (hasActive.value && !document.hidden) timer = window.setTimeout(() => void loadTasks(true), 2000) }
async function resolveSelectedDocument() { /* document links remain available through the source task details */ }
async function loadTasks(isPoll = false) {
  const current = ++version; if (!isPoll) { loading.value = true; loadError.value = '' }
  try {
    const data = await asyncTaskApi.list({ status: statusFilter.value === 'all' ? undefined : statusFilter.value, task_type: typeFilter.value === 'all' ? undefined : typeFilter.value, limit: 100 })
    if (current !== version) return
    tasks.value = data.items; total.value = data.total
    const wanted = typeof route.query.taskId === 'string' ? data.items.find(item => item.task_id === route.query.taskId) : undefined
    if (wanted) { selected.value = wanted; selectionError.value = '' } else if (typeof route.query.taskId === 'string') { selected.value = null; selectionError.value = '任务不存在或不属于当前账号'; void router.replace({ name: 'tasks', query: {} }) } else if (selected.value) selected.value = data.items.find(item => item.task_id === selected.value?.task_id) || null
    if (!selected.value && data.items.length) selected.value = data.items[0]
    failures = 0; await resolveSelectedDocument()
  } catch (error) { if (current === version) { loadError.value = message(error, '任务列表加载失败'); if (++failures >= 3) stopPolling() } } finally { if (current === version) { loading.value = false; if (!loadError.value && failures < 3) schedulePolling() } }
}
function selectTask(task: BackendAsyncTask) { selected.value = task; selectionError.value = ''; exportError.value = ''; void router.replace({ name: 'tasks', query: { taskId: task.task_id } }) }
async function refresh() { failures = 0; stopPolling(); await loadTasks() }
async function loadCourses() { courseLoading.value = true; createError.value = ''; try { courses.value = (await courseApi.list()).items.filter(item => !item.archived) } catch (error) { createError.value = message(error, '课程列表加载失败') } finally { courseLoading.value = false } }
async function openCreate() { showCreate.value = true; createError.value = ''; if (!courses.value.length) await loadCourses() }
async function createWeeklyReport() {
  if (!reportForm.value.start_date || !reportForm.value.end_date) { createError.value = '请选择开始和结束日期'; return }
  const days = (Date.parse(`${reportForm.value.end_date}T00:00:00`) - Date.parse(`${reportForm.value.start_date}T00:00:00`)) / 86400000
  if (days < 0 || days > 30) { createError.value = '结束日期不得早于开始日期，且周期最长为 31 天'; return }
  createLoading.value = true; createError.value = ''
  try { const task = await asyncTaskApi.createWeeklyReport(reportForm.value); showCreate.value = false; selectTask(task); await loadTasks(); ElMessage.success('学习周报任务已创建') } catch (error) { createError.value = message(error, '创建学习周报失败') } finally { createLoading.value = false }
}
async function cancelTask() { if (!selected.value) return; await ElMessageBox.confirm('确认取消此任务？', '取消长时任务', { type: 'warning' }); actionLoading.value = true; try { selected.value = await asyncTaskApi.cancel(selected.value.task_id); await loadTasks(); ElMessage.success('已提交取消请求') } catch (error) { ElMessage.error(message(error, '取消任务失败')) } finally { actionLoading.value = false } }
async function retryTask() { if (!selected.value) return; await ElMessageBox.confirm('确认使用原始输入重新入队？', '重试长时任务', { type: 'warning' }); actionLoading.value = true; try { selected.value = await asyncTaskApi.retry(selected.value.task_id); await loadTasks(); ElMessage.success('任务已重新入队') } catch (error) { ElMessage.error(message(error, '重试任务失败')) } finally { actionLoading.value = false } }
async function downloadReport() { if (!selected.value) return; exportingReport.value = true; exportError.value = ''; try { const result = await asyncTaskApi.downloadWeeklyReport(selected.value.task_id); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.filename; link.click(); URL.revokeObjectURL(url) } catch (error) { exportError.value = message(error, 'Markdown 导出失败') } finally { exportingReport.value = false } }
watch([statusFilter, typeFilter], () => { void router.replace({ name: 'tasks', query: {} }); void loadTasks() }); watch(() => route.query.taskId, () => void loadTasks())
onMounted(() => { document.addEventListener('visibilitychange', refresh); void loadTasks() }); onBeforeUnmount(() => { version++; stopPolling(); document.removeEventListener('visibilitychange', refresh) })
</script>

<template>
  <div><PageHeader title="长时任务中心" eyebrow="ASYNC JOBS" description="查看当前账号真实的文档解析与学习周报任务。"><el-button plain :loading="loading" @click="refresh"><el-icon><RefreshRight /></el-icon>刷新</el-button><el-button type="primary" @click="openCreate"><el-icon><Clock /></el-icon>生成学习周报</el-button></PageHeader>
    <el-alert v-if="loadError" :title="loadError" type="error" :closable="false" show-icon class="alert"><template #default><el-button size="small" @click="refresh">重试</el-button></template></el-alert><el-alert v-if="selectionError" :title="selectionError" type="warning" :closable="false" class="alert" />
    <section class="layout"><article class="content-card list" v-loading="loading"><header><div><h2>任务列表</h2><p>共 {{ total }} 项真实任务</p></div><div><el-select v-model="statusFilter" size="small"><el-option label="全部状态" value="all" /><el-option label="排队中" value="queued" /><el-option label="处理中" value="processing" /><el-option label="成功" value="success" /><el-option label="失败" value="failed" /><el-option label="已取消" value="cancelled" /></el-select><el-select v-model="typeFilter" size="small"><el-option label="全部类型" value="all" /><el-option label="文档解析" value="document_parse" /><el-option label="学习周报" value="weekly_report" /></el-select></div></header><el-empty v-if="!loading && !tasks.length" description="暂无长时任务" /><button v-for="task in tasks" :key="task.task_id" class="entry" :class="{ active: selected?.task_id === task.task_id }" @click="selectTask(task)"><b>{{ labels[task.task_type] || task.task_type }}</b><StatusPill :status="task.status" /><span>{{ steps[task.current_step || ''] || task.current_step || task.task_type }}</span><small>{{ task.task_id }} · {{ dateText(task.created_at) }}</small></button></article>
      <aside v-if="selected" class="content-card detail"><header><StatusPill :status="selected.status" /><h2>{{ labels[selected.task_type] || selected.task_type }}</h2><small>{{ selected.task_id }}</small></header><el-progress :percentage="selected.progress" /><p>{{ steps[selected.current_step || ''] || selected.current_step || '暂无步骤信息' }}</p><el-alert v-if="selected.error_message" :title="selected.error_message" type="error" :closable="false" />
        <section v-if="report" class="report"><div class="report-title"><h3>学习周报</h3><el-button size="small" :loading="exportingReport" @click="downloadReport"><el-icon><Download /></el-icon>下载 Markdown</el-button></div><el-alert v-if="exportError" :title="exportError" type="error" :closable="false" /><p>周期：{{ report.range_start }} 至 {{ report.range_end }} <span v-if="report.timezone">（{{ report.timezone }}）</span></p><div class="metrics"><span>学习 {{ report.total_learning_minutes }} 分钟</span><span>{{ report.study_days }} 个学习日</span><span>{{ report.completed_tasks }} / {{ report.scheduled_tasks }} 任务</span><span v-if="report.scheduled_tasks">完成率 {{ Math.round(report.completion_rate * 100) }}%</span><span v-else>当前周期没有生效计划任务</span></div><div v-if="report.daily" class="table-wrap"><h4>每日学习</h4><table><thead><tr><th>日期</th><th>分钟</th><th>完成</th><th>计划</th></tr></thead><tbody><tr v-for="item in report.daily" :key="item.date"><td>{{ item.date }}</td><td>{{ item.learning_minutes }}</td><td>{{ item.completed_tasks }}</td><td>{{ item.scheduled_tasks }}</td></tr></tbody></table></div><div v-if="report.course_breakdown" class="table-wrap"><h4>课程分布</h4><table><thead><tr><th>课程</th><th>分钟</th><th>完成/计划</th><th>完成率</th></tr></thead><tbody><tr v-for="item in report.course_breakdown" :key="item.course_id"><td>{{ item.course_name }}</td><td>{{ item.learning_minutes }}</td><td>{{ item.completed_tasks }}/{{ item.scheduled_tasks }}</td><td>{{ item.scheduled_tasks ? `${Math.round(item.completion_rate * 100)}%` : '—' }}</td></tr></tbody></table></div><div><h4>薄弱知识点</h4><p v-if="!report.weak_points.length">本周期暂无有真实尝试记录的薄弱知识点</p><ul v-else><li v-for="item in report.weak_points" :key="`${item.course_id || ''}-${item.knowledge_point}`">{{ item.knowledge_point }}<span v-if="item.course_name">（{{ item.course_name }}）</span>：{{ Math.round(item.score * 100) }}%，尝试 {{ item.attempts ?? '—' }} 次，置信度 {{ item.confidence === undefined ? '—' : Math.round(item.confidence * 100) + '%' }}</li></ul></div><p class="summary">基于当前周期真实学习记录与活动计划生成：{{ report.summary }}</p></section>
        <details v-else-if="selected.result_data" class="report"><summary>查看任务结果</summary><pre>{{ JSON.stringify(selected.result_data, null, 2) }}</pre></details><div class="actions"><el-button v-if="selected.can_cancel" type="danger" plain :loading="actionLoading" @click="cancelTask"><el-icon><VideoPause /></el-icon>取消任务</el-button><el-button v-if="selected.can_retry" type="primary" :loading="actionLoading" @click="retryTask"><el-icon><RefreshRight /></el-icon>立即重试</el-button></div></aside><aside v-else class="content-card empty"><el-empty description="选择一项任务查看详情" /></aside></section>
    <el-dialog v-model="showCreate" title="生成学习周报" width="min(460px,92vw)"><el-form label-position="top"><el-form-item label="开始日期"><el-date-picker v-model="reportForm.start_date" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="结束日期"><el-date-picker v-model="reportForm.end_date" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="课程范围"><el-select v-model="reportForm.course_id" clearable placeholder="全部课程" :loading="courseLoading" style="width:100%"><el-option v-for="course in courses" :key="course.id" :value="course.id" :label="course.code ? `${course.name} · ${course.code}` : course.name" /></el-select></el-form-item></el-form><el-alert v-if="createError" :title="createError" type="error" :closable="false" /><template #footer><el-button @click="showCreate = false">取消</el-button><el-button type="primary" :loading="createLoading" @click="createWeeklyReport">创建任务</el-button></template></el-dialog></div>
</template>

<style scoped>
.alert{margin-bottom:16px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:16px}.list{overflow:hidden}.list header,.detail header{display:flex;justify-content:space-between;gap:10px;padding:16px;border-bottom:1px solid var(--line)}h2,h3,h4{margin:0}.list header p{margin:4px 0 0;color:#8791a5;font-size:12px}.list header .el-select{width:108px;margin-left:6px}.entry{display:grid;grid-template-columns:1fr auto;gap:5px;width:100%;padding:14px 16px;border:0;border-bottom:1px solid #edf0f4;background:#fff;text-align:left;cursor:pointer}.entry.active,.entry:hover{background:#f5f7ff}.entry span,.entry small{grid-column:1/-1;color:#7c8699;font-size:12px}.detail{min-width:0;padding-bottom:16px}.detail>p,.report{margin:16px}.report{padding:14px;border-radius:10px;background:#f6f8fd;color:#526078;font-size:13px;line-height:1.7}.report-title{display:flex;justify-content:space-between;gap:8px;align-items:center}.metrics{display:flex;flex-wrap:wrap;gap:8px}.metrics span{padding:3px 7px;border-radius:999px;background:#e9edff}.table-wrap{overflow-x:auto;margin-top:14px}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:6px;border-bottom:1px solid #dfe4ef;text-align:left}.summary{margin-bottom:0}.report ul{padding-left:18px}.report pre{overflow:auto}.actions{display:flex;gap:8px;margin:16px}.empty{display:grid;place-items:center;min-height:280px}@media(max-width:1000px){.layout{grid-template-columns:1fr}.detail,.empty{display:block}.empty{min-height:160px}}@media(max-width:600px){.list header{align-items:flex-start;flex-direction:column}.list header .el-select{width:calc(50% - 4px);margin:0 4px 0 0}.report{margin:10px;padding:10px}.detail>p{margin:10px}}
</style>
