<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Calendar, Download } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import { calendarApi, courseApi, mcpApi } from '@/api/services'
import { getApiErrorMessage } from '@/api/client'
import type { CalendarEventItem, CalendarPlanSyncPreview, CourseListItem, MCPToolCallItem, MCPToolInfo } from '@/types'
const route=useRoute();const router=useRouter();const courses=ref<CourseListItem[]>([]);const events=ref<CalendarEventItem[]>([]);const tools=ref<MCPToolInfo[]>([]);const calls=ref<MCPToolCallItem[]>([]);const error=ref('');const exportError=ref('');const loading=ref(false);const weekStart=ref('');const courseId=ref<number|undefined>();const preview=ref<CalendarPlanSyncPreview|null>(null);const syncVisible=ref(false);const dailyStart=ref('20:00');const gap=ref(10)
function monday(value:Date){const d=new Date(value);d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}
function dates(){const s=new Date(weekStart.value+'T00:00:00');const e=new Date(s);e.setDate(e.getDate()+7);return{start_at:s.toISOString(),end_at:e.toISOString()}}
const days=computed(()=>Array.from({length:7},(_,i)=>{const d=new Date(weekStart.value+'T00:00:00');d.setDate(d.getDate()+i);return d.toISOString().slice(0,10)}))
async function load(){loading.value=true;error.value='';events.value=[];try{courses.value=(await courseApi.list()).items.filter(x=>!x.archived);const raw=String(route.query.weekStart||'');weekStart.value=/^\d{4}-\d{2}-\d{2}$/.test(raw)?monday(new Date(raw+'T00:00:00')):monday(new Date());const id=Number(route.query.courseId);courseId.value=courses.value.some(c=>c.id===id)?id:undefined;const r=dates();const data=await Promise.all([calendarApi.list({start_at:r.start_at,end_at:r.end_at,course_id:courseId.value}),mcpApi.listTools(),mcpApi.listCalls({calendar_only:true})]);events.value=data[0].items;tools.value=data[1].items;calls.value=data[2].items}catch(e){error.value=getApiErrorMessage(e,'日历加载失败')}finally{loading.value=false}}
function changeWeek(n:number){const d=new Date(weekStart.value+'T00:00:00');d.setDate(d.getDate()+n*7);weekStart.value=d.toISOString().slice(0,10);void router.replace({query:{weekStart:weekStart.value,...(courseId.value?{courseId:String(courseId.value)}:{})}});void load()}
async function planPreview(){try{preview.value=await calendarApi.previewPlanSync({start_date:weekStart.value,end_date:days.value[6],course_id:courseId.value,daily_start_time:dailyStart.value,gap_minutes:gap.value})}catch(e){error.value=getApiErrorMessage(e,'计划预览失败')}}
async function confirm(){if(!preview.value)return;try{await calendarApi.confirmPlanSync(preview.value,preview.value.confirmation_token);syncVisible.value=false;await load()}catch(e){error.value=getApiErrorMessage(e,'计划同步失败')}}
async function exportIcs(){exportError.value='';try{const r=dates();const file=await calendarApi.exportIcs({start_at:r.start_at,end_at:r.end_at,course_id:courseId.value});const url=URL.createObjectURL(file.blob);const a=document.createElement('a');a.href=url;a.download=file.filename;a.click();URL.revokeObjectURL(url)}catch(e){exportError.value=getApiErrorMessage(e,'ICS 导出失败')}}
onMounted(load)
</script>
<template><div><PageHeader title="学习日历" eyebrow="LOCAL LEARNING CALENDAR" description="将当前活动学习计划同步到 StudyPilot 本地日历，并可导出 ICS 文件。"><el-select v-model="courseId" clearable placeholder="全部课程" @change="load"><el-option v-for="c in courses" :key="c.id" :label="c.name" :value="c.id"/></el-select><el-button plain @click="exportIcs"><el-icon><Download/></el-icon>导出 ICS</el-button><el-button type="primary" @click="syncVisible=true"><el-icon><Calendar/></el-icon>同步学习计划</el-button></PageHeader><el-alert v-if="exportError" :title="exportError" type="error"/><el-alert v-if="error" :title="error" type="error"/><div v-else-if="loading" v-loading="true" class="loading"/><el-empty v-else-if="!courses.length" description="暂无真实课程，请先创建课程"/><section v-else class="layout"><main><article class="content-card card-pad"><b>StudyPilot 本地日历：可用</b><p>外部日历账户：未连接；ICS 导出可用于手动导入 Outlook、Google Calendar 等应用。</p></article><article class="content-card card-pad"><div class="head"><h2>自然周安排</h2><span>{{weekStart}} 至 {{days[6]}}</span><el-button size="small" @click="changeWeek(-1)">上一周</el-button><el-button size="small" @click="changeWeek(1)">下一周</el-button></div><el-empty v-if="!events.length" description="当前周暂无本地日历事件"/><div v-else class="days"><div v-for="day in days" :key="day"><h3>{{day}}</h3><div v-for="event in events.filter(e=>e.start_at.slice(0,10)===day)" :key="event.id" class="event"><b>{{event.title}}</b><small>{{event.start_at.slice(11,16)}}–{{event.end_at.slice(11,16)}} · {{event.course_name||'本地事件'}}</small></div></div></div></article></main><aside><article class="content-card card-pad"><h2>MCP 日历工具</h2><p>已注册 {{tools.length}} 个工具；写操作需要二次确认。</p><div v-for="tool in tools.filter(t=>t.name.includes('calendar')||t.name==='get_available_time')" :key="tool.name">{{tool.name}} · {{tool.requires_confirmation?'写操作':'只读'}}</div></article><article class="content-card card-pad"><h2>最近 MCP 日历调用</h2><el-empty v-if="!calls.length" description="暂无 MCP 日历调用记录"/><div v-for="call in calls" :key="call.id">{{call.tool_name}} · {{call.status}}</div></article></aside></section><el-dialog v-model="syncVisible" title="同步学习计划到本地日历"><el-form label-position="top"><el-form-item label="每日开始时间"><el-time-select v-model="dailyStart" start="06:00" step="00:30" end="23:30"/></el-form-item><el-form-item label="任务间隔"><el-input-number v-model="gap" :min="0" :max="120"/></el-form-item></el-form><el-button @click="planPreview">生成真实预览</el-button><div v-if="preview"><p>可创建 {{preview.ready_count}} 项；冲突 {{preview.conflict_count}} 项；已同步 {{preview.already_synced_count}} 项。</p><div v-for="item in preview.items" :key="item.task_id">{{item.title}} · {{item.status}} · {{item.reason}}</div></div><template #footer><el-button @click="syncVisible=false">取消</el-button><el-button type="primary" :disabled="!preview||!preview.ready_count" @click="confirm">确认创建</el-button></template></el-dialog></div></template>
<style scoped>.layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:16px}.head{display:flex;align-items:center;gap:8px}.head span{flex:1;color:#8791a4;font-size:9px}.days{display:grid;grid-template-columns:repeat(7,minmax(120px,1fr));gap:8px;overflow:auto}.days>div{min-height:150px;border:1px solid #e8ebf1;padding:8px}.days h3{font-size:9px}.event{margin:6px 0;padding:8px;border-left:3px solid #5e6de7;background:#eff1ff}.event b,.event small{display:block;font-size:8px}.event small{margin-top:4px;color:#7d879b}.loading{min-height:420px}@media(max-width:900px){.layout{grid-template-columns:1fr}}</style>
