<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import PageHeader from '@/components/PageHeader.vue'
import { courseApi, practiceApi } from '@/api/services'
import { getApiErrorMessage } from '@/api/client'
import type { CourseListItem, PracticeAttemptResult, PracticeQuestion, PracticeSummary } from '@/types'
const route=useRoute(),router=useRouter(); const courses=ref<CourseListItem[]>([]),courseId=ref<number|null>(null),questions=ref<PracticeQuestion[]>([]),summary=ref<PracticeSummary|null>(null),index=ref(0),selected=ref(''),result=ref<PracticeAttemptResult|null>(null),loading=ref(false),booting=ref(false),error=ref(''),started=ref(Date.now())
const mode=computed(()=>route.query.mode==='wrong'?'wrong':'all'); const question=computed(()=>questions.value[index.value]); const progress=computed(()=>questions.value.length?Math.round((index.value+1)/questions.value.length*100):0)
async function load(){loading.value=true;error.value='';try{courses.value=(await courseApi.list()).items.filter(x=>!x.archived); const raw=Number(route.query.courseId);courseId.value=courses.value.some(x=>x.id===raw)?raw:(courses.value[0]?.id??null);if(courseId.value){const data=await practiceApi.questions(courseId.value,mode.value);questions.value=data.items;summary.value=data.summary;index.value=0;selected.value='';result.value=null;if(String(courseId.value)!==route.query.courseId)await router.replace({query:{...route.query,courseId:String(courseId.value),mode:mode.value}})}}catch(e){error.value=getApiErrorMessage(e,'练习加载失败')}finally{loading.value=false}}
async function bootstrap(){if(!courseId.value)return;booting.value=true;try{await practiceApi.bootstrap(courseId.value);await load()}catch(e){ElMessage.error(getApiErrorMessage(e,'生成基础自测题失败'))}finally{booting.value=false}}
async function submit(){if(!courseId.value||!question.value||!selected.value)return;try{result.value=await practiceApi.submit(courseId.value,question.value.id,{submission_id:crypto.randomUUID(),selected_option:selected.value,elapsed_seconds:Math.max(0,Math.round((Date.now()-started.value)/1000))});summary.value=result.value.summary}catch(e){ElMessage.error(getApiErrorMessage(e,'提交失败'))}}
function move(step:number){index.value=Math.max(0,Math.min(questions.value.length-1,index.value+step));selected.value='';result.value=null;started.value=Date.now()}
watch(()=>[route.query.courseId,route.query.mode],()=>void load());onMounted(load)
</script>
<template><div><PageHeader :title="mode==='wrong'?'错题复习':'练习答题'" eyebrow="SMART PRACTICE" :description="question ? `当前课程：${courses.find(x=>x.id===courseId)?.name}` : '选择真实课程并完成基础自测'" ><el-select v-model="courseId" style="width:200px" @change="router.replace({query:{courseId:String(courseId),mode}})"><el-option v-for="c in courses" :key="c.id" :label="c.name" :value="c.id"/></el-select></PageHeader><el-alert v-if="error" :title="error" type="error"/><div v-else v-loading="loading"><el-empty v-if="!courseId" description="暂无真实课程"/><el-empty v-else-if="!questions.length" :description="mode==='wrong'?'没有待复习错题':'暂无题目；请先生成并确认学习计划以获得知识点'" ><el-button v-if="mode==='all'" type="primary" :loading="booting" @click="bootstrap">生成基础自测题</el-button></el-empty><section v-else class="content-card card-pad"><el-progress :percentage="progress"/><p>{{ index+1 }} / {{ questions.length }} · 当前正确率 {{ Math.round((summary?.accuracy||0)*100) }}%</p><h2>{{question.stem}}</h2><el-radio-group v-model="selected" :disabled="!!result"><el-radio v-for="o in question.options" :key="o.key" :value="o.key" border>{{o.key}}. {{o.text}}</el-radio></el-radio-group><div v-if="result" class="result"><b>{{result.is_correct?'回答正确':'回答错误，正确答案：'+result.correct_option}}</b><p>{{result.explanation}}</p><p>规则提示：关联知识点 {{result.knowledge_point||'未关联'}}；当前掌握度 {{result.mastery_score===null?'暂无':Math.round(result.mastery_score*100)+'%'}}</p><el-button v-if="!result.is_correct" @click="router.push({name:'wrong-book',query:{courseId}})">查看错题本</el-button></div><footer><el-button :disabled="index===0" @click="move(-1)">上一题</el-button><el-button v-if="!result" type="primary" :disabled="!selected" @click="submit">提交答案</el-button><el-button v-else type="primary" :disabled="index===questions.length-1" @click="move(1)">下一题</el-button></footer></section></div></div></template>
<style scoped>.card-pad{padding:24px}.el-radio-group{display:grid;gap:10px;margin:20px 0}.result{margin:18px 0;padding:14px;background:#f5f8ff;border-radius:10px}footer{display:flex;justify-content:space-between}</style>
