<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'; import { useRoute,useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import PageHeader from '@/components/PageHeader.vue'; import {courseApi,practiceApi} from '@/api/services'; import {getApiErrorMessage} from '@/api/client'; import type {CourseListItem,WrongBookEntry} from '@/types'
const route=useRoute(),router=useRouter(),courses=ref<CourseListItem[]>([]),courseId=ref<number|null>(null),items=ref<WrongBookEntry[]>([]),summary=ref({pending:0,mastered:0,repeated_wrong:0}),status=ref('all'),q=ref(''),loading=ref(false),error=ref(''),expanded=ref<number|null>(null)
async function load(){loading.value=true;error.value='';try{courses.value=(await courseApi.list()).items.filter(x=>!x.archived);const raw=Number(route.query.courseId);courseId.value=courses.value.some(x=>x.id===raw)?raw:(courses.value[0]?.id??null);if(courseId.value){const data=await practiceApi.wrongBook(courseId.value,status.value,q.value);items.value=data.items;summary.value=data.summary;if(String(courseId.value)!==route.query.courseId)await router.replace({query:{courseId:String(courseId.value)}})}}catch(e){error.value=getApiErrorMessage(e,'错题本加载失败')}finally{loading.value=false}}
async function update(id:number,next:'mastered'|'removed'){if(!courseId.value)return;try{await practiceApi.updateWrong(courseId.value,id,next);await load()}catch(e){ElMessage.error(getApiErrorMessage(e,'操作失败'))}}
watch(()=>route.query.courseId,()=>void load());onMounted(load)
</script>
<template><div><PageHeader title="错题本" eyebrow="ERROR REVIEW" description="真实错题、掌握度和规则复习提示。"><el-select v-model="courseId" style="width:200px" @change="router.replace({query:{courseId:String(courseId)}})"><el-option v-for="c in courses" :key="c.id" :value="c.id" :label="c.name"/></el-select><el-button type="primary" :disabled="!summary.pending" @click="router.push({name:'practice',query:{courseId,mode:'wrong'}})">开始错题复习</el-button></PageHeader><el-alert v-if="error" :title="error" type="error"/><div v-else v-loading="loading"><section class="summary"><div>待掌握 <b>{{summary.pending}}</b></div><div>重复错误 <b>{{summary.repeated_wrong}}</b></div><div>已掌握 <b>{{summary.mastered}}</b></div></section><div class="toolbar"><el-radio-group v-model="status" @change="load"><el-radio-button value="all">全部</el-radio-button><el-radio-button value="pending">待掌握</el-radio-button><el-radio-button value="mastered">已掌握</el-radio-button></el-radio-group><el-input v-model="q" placeholder="搜索题干或知识点" @change="load"/></div><el-empty v-if="!items.length" description="没有符合条件的真实错题"/><article v-for="item in items" :key="item.id" class="content-card item"><h2>{{item.question.stem}}</h2><p>{{item.question.knowledge_point||'未关联知识点'}} · 错误 {{item.wrong_count}} 次 · 你的答案 {{item.last_selected_option}} → 正确答案 {{item.question.correct_option}}</p><el-button text @click="expanded=expanded===item.id?null:item.id">查看解析</el-button><p v-if="expanded===item.id" class="explain">错题解析：{{item.question.explanation}}</p><el-button v-if="item.status==='pending'" @click="update(item.id,'mastered')">标记已掌握</el-button><el-button text type="danger" @click="update(item.id,'removed')">移除</el-button></article></div></div></template>
<style scoped>.summary{display:flex;gap:14px;margin-bottom:15px}.summary div,.item{padding:16px}.summary div{flex:1;background:#fff;border-radius:10px}.summary b{font-size:20px}.toolbar{display:flex;gap:12px;margin-bottom:14px}.item{margin-bottom:10px}.item h2{font-size:13px}.item p,.explain{font-size:10px;color:#65728a}</style>
